### ISSUE TITLE
Canvas Package

### ISSUE THREAD

**Issue by Jasper-aaa** [Divadi/DetMatch#3]
Thanks for your error report and we appreciate it a lot.

**Checklist**
1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.
3. I can not find the matched Python Canvas package on both Internet and provided conda/requirements environment list 

**Describe the bug**
The Canvas package used in "mmdet3d/models/ssl_modules/consumers/visualize.py"
from canvas import Canvas
I can't find the matched canvas package in python that possess methods like draw_lines get_canvas_coords

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated! Or please give a instruction pip order of how to correctly install the corresponding Canvas package.

**Comment by gaiming312** [comment]
Have you solved the problem? I had the same mistake.

**Comment by Divadi** [comment]
Apologies for delayed response - here it is.
It's a modified version of my [simple_plot3d](https://github.com/Divadi/simple_plot3d/tree/main) canvas.
https://gist.github.com/Divadi/2a02b7af9c384901e6aae5b944388cbb
