### ISSUE TITLE
Questions about the "kitti_infos_train_proj_3d.pkl" file

### ISSUE THREAD

**Issue by TimGor1997** [Divadi/DetMatch#5]
Dear author, I would like to ask how the file "kitti_infos_train_proj_3d.pkl" is produced? Including several other ".pkl "files, is it the same as OpenPCDet?
I look forward to your response.
Best regards!

**Comment by Divadi** [comment]
This is simply the original pkl files with the 2D boxes generated by projecting the 3D boxes. The original uses human-annotated 2D boxes.
